image: ${CI_REGISTRY}/devops/images/usgs/python:3.9

stages:
  - build
  - lint
  - test

poetry:
  stage: build
  artifacts:
    paths:
      - poetry.toml
      - .venv
    expire_in: 1 week
  script:
    - poetry config virtualenvs.in-project true --local
    - poetry install

lint:
  stage: lint
  script:
    - poetry run poe lint

test:
  stage: test
  script:
    - poetry run poe test
